### ISSUE TITLE
Guild Creation Bug

### ISSUE THREAD

**Issue by CNDev** [andresantacruz/W2PP#15]
I cannot create guild, please take a look about this thing.

**Comment by AndersonGIT** [comment]
I tried and it worked well, make sure that you have a kingdom already. It might solve the problem.
Please answer this for any case.
AmmDy

**Comment by CNDev** [comment]
I see, i'll check it out..

**Comment by CNDev** [comment]
how about the bug on learning skills using book?

**Comment by AndersonGIT** [comment]
About that I don't know, didn't check it out yet.
Any success on creating the guild?
AmmDy

**Comment by CNDev** [comment]
mind giving me your skype id?

**Comment by AndersonGIT** [comment]
No problem, you can find me searching for:
AmmDy.AmmDy
